/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMasRouteImport } from './routes/_authenticated/mas'
import { Route as AuthenticatedMPlantelRouteImport } from './routes/_authenticated/m.plantel'
import { Route as AuthenticatedMCalendarioRouteImport } from './routes/_authenticated/m.calendario'
import { Route as AuthenticatedMModuleRouteImport } from './routes/_authenticated/m.$module'
import { Route as AuthenticatedMPlantelPlayerIdRouteImport } from './routes/_authenticated/m.plantel.$playerId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasRoute = AuthenticatedMasRouteImport.update({
  id: '/mas',
  path: '/mas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMPlantelRoute = AuthenticatedMPlantelRouteImport.update({
  id: '/m/plantel',
  path: '/m/plantel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMCalendarioRoute =
  AuthenticatedMCalendarioRouteImport.update({
    id: '/m/calendario',
    path: '/m/calendario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMModuleRoute = AuthenticatedMModuleRouteImport.update({
  id: '/m/$module',
  path: '/m/$module',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMPlantelPlayerIdRoute =
  AuthenticatedMPlantelPlayerIdRouteImport.update({
    id: '/$playerId',
    path: '/$playerId',
    getParentRoute: () => AuthenticatedMPlantelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/mas': typeof AuthenticatedMasRoute
  '/m/$module': typeof AuthenticatedMModuleRoute
  '/m/calendario': typeof AuthenticatedMCalendarioRoute
  '/m/plantel': typeof AuthenticatedMPlantelRouteWithChildren
  '/m/plantel/$playerId': typeof AuthenticatedMPlantelPlayerIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/mas': typeof AuthenticatedMasRoute
  '/': typeof AuthenticatedIndexRoute
  '/m/$module': typeof AuthenticatedMModuleRoute
  '/m/calendario': typeof AuthenticatedMCalendarioRoute
  '/m/plantel': typeof AuthenticatedMPlantelRouteWithChildren
  '/m/plantel/$playerId': typeof AuthenticatedMPlantelPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/mas': typeof AuthenticatedMasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/m/$module': typeof AuthenticatedMModuleRoute
  '/_authenticated/m/calendario': typeof AuthenticatedMCalendarioRoute
  '/_authenticated/m/plantel': typeof AuthenticatedMPlantelRouteWithChildren
  '/_authenticated/m/plantel/$playerId': typeof AuthenticatedMPlantelPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mas'
    | '/m/$module'
    | '/m/calendario'
    | '/m/plantel'
    | '/m/plantel/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/mas'
    | '/'
    | '/m/$module'
    | '/m/calendario'
    | '/m/plantel'
    | '/m/plantel/$playerId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/mas'
    | '/_authenticated/'
    | '/_authenticated/m/$module'
    | '/_authenticated/m/calendario'
    | '/_authenticated/m/plantel'
    | '/_authenticated/m/plantel/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mas': {
      id: '/_authenticated/mas'
      path: '/mas'
      fullPath: '/mas'
      preLoaderRoute: typeof AuthenticatedMasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/plantel': {
      id: '/_authenticated/m/plantel'
      path: '/m/plantel'
      fullPath: '/m/plantel'
      preLoaderRoute: typeof AuthenticatedMPlantelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/calendario': {
      id: '/_authenticated/m/calendario'
      path: '/m/calendario'
      fullPath: '/m/calendario'
      preLoaderRoute: typeof AuthenticatedMCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/$module': {
      id: '/_authenticated/m/$module'
      path: '/m/$module'
      fullPath: '/m/$module'
      preLoaderRoute: typeof AuthenticatedMModuleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/plantel/$playerId': {
      id: '/_authenticated/m/plantel/$playerId'
      path: '/$playerId'
      fullPath: '/m/plantel/$playerId'
      preLoaderRoute: typeof AuthenticatedMPlantelPlayerIdRouteImport
      parentRoute: typeof AuthenticatedMPlantelRoute
    }
  }
}

interface AuthenticatedMPlantelRouteChildren {
  AuthenticatedMPlantelPlayerIdRoute: typeof AuthenticatedMPlantelPlayerIdRoute
}

const AuthenticatedMPlantelRouteChildren: AuthenticatedMPlantelRouteChildren = {
  AuthenticatedMPlantelPlayerIdRoute: AuthenticatedMPlantelPlayerIdRoute,
}

const AuthenticatedMPlantelRouteWithChildren =
  AuthenticatedMPlantelRoute._addFileChildren(
    AuthenticatedMPlantelRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMasRoute: typeof AuthenticatedMasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMModuleRoute: typeof AuthenticatedMModuleRoute
  AuthenticatedMCalendarioRoute: typeof AuthenticatedMCalendarioRoute
  AuthenticatedMPlantelRoute: typeof AuthenticatedMPlantelRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMasRoute: AuthenticatedMasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMModuleRoute: AuthenticatedMModuleRoute,
  AuthenticatedMCalendarioRoute: AuthenticatedMCalendarioRoute,
  AuthenticatedMPlantelRoute: AuthenticatedMPlantelRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
