/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedMiPerfilRouteImport } from './routes/_authenticated/mi-perfil'
import { Route as AuthenticatedMiClubRouteImport } from './routes/_authenticated/mi-club'
import { Route as AuthenticatedCoordinacionRouteImport } from './routes/_authenticated/coordinacion'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMUsuariosRouteImport } from './routes/_authenticated/m.usuarios'
import { Route as AuthenticatedMPlantelRouteImport } from './routes/_authenticated/m.plantel'
import { Route as AuthenticatedMMesRouteImport } from './routes/_authenticated/m.mes'
import { Route as AuthenticatedMInventarioRouteImport } from './routes/_authenticated/m.inventario'
import { Route as AuthenticatedMDocumentosRouteImport } from './routes/_authenticated/m.documentos'
import { Route as AuthenticatedMCoordinacion_internaRouteImport } from './routes/_authenticated/m.coordinacion_interna'
import { Route as AuthenticatedMAgendaRouteImport } from './routes/_authenticated/m.agenda'
import { Route as AuthenticatedMModuleRouteImport } from './routes/_authenticated/m.$module'
import { Route as AuthenticatedAdminClubsRouteImport } from './routes/_authenticated/admin.clubs'
import { Route as AuthenticatedMPlantelPlayerIdRouteImport } from './routes/_authenticated/m.plantel.$playerId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMiPerfilRoute = AuthenticatedMiPerfilRouteImport.update({
  id: '/mi-perfil',
  path: '/mi-perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiClubRoute = AuthenticatedMiClubRouteImport.update({
  id: '/mi-club',
  path: '/mi-club',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoordinacionRoute =
  AuthenticatedCoordinacionRouteImport.update({
    id: '/coordinacion',
    path: '/coordinacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMUsuariosRoute = AuthenticatedMUsuariosRouteImport.update({
  id: '/m/usuarios',
  path: '/m/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMPlantelRoute = AuthenticatedMPlantelRouteImport.update({
  id: '/m/plantel',
  path: '/m/plantel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMMesRoute = AuthenticatedMMesRouteImport.update({
  id: '/m/mes',
  path: '/m/mes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMInventarioRoute =
  AuthenticatedMInventarioRouteImport.update({
    id: '/m/inventario',
    path: '/m/inventario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMDocumentosRoute =
  AuthenticatedMDocumentosRouteImport.update({
    id: '/m/documentos',
    path: '/m/documentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMCoordinacion_internaRoute =
  AuthenticatedMCoordinacion_internaRouteImport.update({
    id: '/m/coordinacion_interna',
    path: '/m/coordinacion_interna',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMAgendaRoute = AuthenticatedMAgendaRouteImport.update({
  id: '/m/agenda',
  path: '/m/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMModuleRoute = AuthenticatedMModuleRouteImport.update({
  id: '/m/$module',
  path: '/m/$module',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminClubsRoute = AuthenticatedAdminClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedMPlantelPlayerIdRoute =
  AuthenticatedMPlantelPlayerIdRouteImport.update({
    id: '/$playerId',
    path: '/$playerId',
    getParentRoute: () => AuthenticatedMPlantelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/agenda': typeof AuthenticatedAgendaRoute
  '/coordinacion': typeof AuthenticatedCoordinacionRoute
  '/mi-club': typeof AuthenticatedMiClubRoute
  '/mi-perfil': typeof AuthenticatedMiPerfilRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/clubs': typeof AuthenticatedAdminClubsRoute
  '/m/$module': typeof AuthenticatedMModuleRoute
  '/m/agenda': typeof AuthenticatedMAgendaRoute
  '/m/coordinacion_interna': typeof AuthenticatedMCoordinacion_internaRoute
  '/m/documentos': typeof AuthenticatedMDocumentosRoute
  '/m/inventario': typeof AuthenticatedMInventarioRoute
  '/m/mes': typeof AuthenticatedMMesRoute
  '/m/plantel': typeof AuthenticatedMPlantelRouteWithChildren
  '/m/usuarios': typeof AuthenticatedMUsuariosRoute
  '/m/plantel/$playerId': typeof AuthenticatedMPlantelPlayerIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/agenda': typeof AuthenticatedAgendaRoute
  '/coordinacion': typeof AuthenticatedCoordinacionRoute
  '/mi-club': typeof AuthenticatedMiClubRoute
  '/mi-perfil': typeof AuthenticatedMiPerfilRoute
  '/invite/$token': typeof InviteTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/clubs': typeof AuthenticatedAdminClubsRoute
  '/m/$module': typeof AuthenticatedMModuleRoute
  '/m/agenda': typeof AuthenticatedMAgendaRoute
  '/m/coordinacion_interna': typeof AuthenticatedMCoordinacion_internaRoute
  '/m/documentos': typeof AuthenticatedMDocumentosRoute
  '/m/inventario': typeof AuthenticatedMInventarioRoute
  '/m/mes': typeof AuthenticatedMMesRoute
  '/m/plantel': typeof AuthenticatedMPlantelRouteWithChildren
  '/m/usuarios': typeof AuthenticatedMUsuariosRoute
  '/m/plantel/$playerId': typeof AuthenticatedMPlantelPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/coordinacion': typeof AuthenticatedCoordinacionRoute
  '/_authenticated/mi-club': typeof AuthenticatedMiClubRoute
  '/_authenticated/mi-perfil': typeof AuthenticatedMiPerfilRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/clubs': typeof AuthenticatedAdminClubsRoute
  '/_authenticated/m/$module': typeof AuthenticatedMModuleRoute
  '/_authenticated/m/agenda': typeof AuthenticatedMAgendaRoute
  '/_authenticated/m/coordinacion_interna': typeof AuthenticatedMCoordinacion_internaRoute
  '/_authenticated/m/documentos': typeof AuthenticatedMDocumentosRoute
  '/_authenticated/m/inventario': typeof AuthenticatedMInventarioRoute
  '/_authenticated/m/mes': typeof AuthenticatedMMesRoute
  '/_authenticated/m/plantel': typeof AuthenticatedMPlantelRouteWithChildren
  '/_authenticated/m/usuarios': typeof AuthenticatedMUsuariosRoute
  '/_authenticated/m/plantel/$playerId': typeof AuthenticatedMPlantelPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/agenda'
    | '/coordinacion'
    | '/mi-club'
    | '/mi-perfil'
    | '/invite/$token'
    | '/admin/clubs'
    | '/m/$module'
    | '/m/agenda'
    | '/m/coordinacion_interna'
    | '/m/documentos'
    | '/m/inventario'
    | '/m/mes'
    | '/m/plantel'
    | '/m/usuarios'
    | '/m/plantel/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/agenda'
    | '/coordinacion'
    | '/mi-club'
    | '/mi-perfil'
    | '/invite/$token'
    | '/'
    | '/admin/clubs'
    | '/m/$module'
    | '/m/agenda'
    | '/m/coordinacion_interna'
    | '/m/documentos'
    | '/m/inventario'
    | '/m/mes'
    | '/m/plantel'
    | '/m/usuarios'
    | '/m/plantel/$playerId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/agenda'
    | '/_authenticated/coordinacion'
    | '/_authenticated/mi-club'
    | '/_authenticated/mi-perfil'
    | '/invite/$token'
    | '/_authenticated/'
    | '/_authenticated/admin/clubs'
    | '/_authenticated/m/$module'
    | '/_authenticated/m/agenda'
    | '/_authenticated/m/coordinacion_interna'
    | '/_authenticated/m/documentos'
    | '/_authenticated/m/inventario'
    | '/_authenticated/m/mes'
    | '/_authenticated/m/plantel'
    | '/_authenticated/m/usuarios'
    | '/_authenticated/m/plantel/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mi-perfil': {
      id: '/_authenticated/mi-perfil'
      path: '/mi-perfil'
      fullPath: '/mi-perfil'
      preLoaderRoute: typeof AuthenticatedMiPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-club': {
      id: '/_authenticated/mi-club'
      path: '/mi-club'
      fullPath: '/mi-club'
      preLoaderRoute: typeof AuthenticatedMiClubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coordinacion': {
      id: '/_authenticated/coordinacion'
      path: '/coordinacion'
      fullPath: '/coordinacion'
      preLoaderRoute: typeof AuthenticatedCoordinacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/usuarios': {
      id: '/_authenticated/m/usuarios'
      path: '/m/usuarios'
      fullPath: '/m/usuarios'
      preLoaderRoute: typeof AuthenticatedMUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/plantel': {
      id: '/_authenticated/m/plantel'
      path: '/m/plantel'
      fullPath: '/m/plantel'
      preLoaderRoute: typeof AuthenticatedMPlantelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/mes': {
      id: '/_authenticated/m/mes'
      path: '/m/mes'
      fullPath: '/m/mes'
      preLoaderRoute: typeof AuthenticatedMMesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/inventario': {
      id: '/_authenticated/m/inventario'
      path: '/m/inventario'
      fullPath: '/m/inventario'
      preLoaderRoute: typeof AuthenticatedMInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/documentos': {
      id: '/_authenticated/m/documentos'
      path: '/m/documentos'
      fullPath: '/m/documentos'
      preLoaderRoute: typeof AuthenticatedMDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/coordinacion_interna': {
      id: '/_authenticated/m/coordinacion_interna'
      path: '/m/coordinacion_interna'
      fullPath: '/m/coordinacion_interna'
      preLoaderRoute: typeof AuthenticatedMCoordinacion_internaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/agenda': {
      id: '/_authenticated/m/agenda'
      path: '/m/agenda'
      fullPath: '/m/agenda'
      preLoaderRoute: typeof AuthenticatedMAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/m/$module': {
      id: '/_authenticated/m/$module'
      path: '/m/$module'
      fullPath: '/m/$module'
      preLoaderRoute: typeof AuthenticatedMModuleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/clubs': {
      id: '/_authenticated/admin/clubs'
      path: '/clubs'
      fullPath: '/admin/clubs'
      preLoaderRoute: typeof AuthenticatedAdminClubsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/m/plantel/$playerId': {
      id: '/_authenticated/m/plantel/$playerId'
      path: '/$playerId'
      fullPath: '/m/plantel/$playerId'
      preLoaderRoute: typeof AuthenticatedMPlantelPlayerIdRouteImport
      parentRoute: typeof AuthenticatedMPlantelRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClubsRoute: typeof AuthenticatedAdminClubsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClubsRoute: AuthenticatedAdminClubsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMPlantelRouteChildren {
  AuthenticatedMPlantelPlayerIdRoute: typeof AuthenticatedMPlantelPlayerIdRoute
}

const AuthenticatedMPlantelRouteChildren: AuthenticatedMPlantelRouteChildren = {
  AuthenticatedMPlantelPlayerIdRoute: AuthenticatedMPlantelPlayerIdRoute,
}

const AuthenticatedMPlantelRouteWithChildren =
  AuthenticatedMPlantelRoute._addFileChildren(
    AuthenticatedMPlantelRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedCoordinacionRoute: typeof AuthenticatedCoordinacionRoute
  AuthenticatedMiClubRoute: typeof AuthenticatedMiClubRoute
  AuthenticatedMiPerfilRoute: typeof AuthenticatedMiPerfilRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMModuleRoute: typeof AuthenticatedMModuleRoute
  AuthenticatedMAgendaRoute: typeof AuthenticatedMAgendaRoute
  AuthenticatedMCoordinacion_internaRoute: typeof AuthenticatedMCoordinacion_internaRoute
  AuthenticatedMDocumentosRoute: typeof AuthenticatedMDocumentosRoute
  AuthenticatedMInventarioRoute: typeof AuthenticatedMInventarioRoute
  AuthenticatedMMesRoute: typeof AuthenticatedMMesRoute
  AuthenticatedMPlantelRoute: typeof AuthenticatedMPlantelRouteWithChildren
  AuthenticatedMUsuariosRoute: typeof AuthenticatedMUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedCoordinacionRoute: AuthenticatedCoordinacionRoute,
  AuthenticatedMiClubRoute: AuthenticatedMiClubRoute,
  AuthenticatedMiPerfilRoute: AuthenticatedMiPerfilRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMModuleRoute: AuthenticatedMModuleRoute,
  AuthenticatedMAgendaRoute: AuthenticatedMAgendaRoute,
  AuthenticatedMCoordinacion_internaRoute:
    AuthenticatedMCoordinacion_internaRoute,
  AuthenticatedMDocumentosRoute: AuthenticatedMDocumentosRoute,
  AuthenticatedMInventarioRoute: AuthenticatedMInventarioRoute,
  AuthenticatedMMesRoute: AuthenticatedMMesRoute,
  AuthenticatedMPlantelRoute: AuthenticatedMPlantelRouteWithChildren,
  AuthenticatedMUsuariosRoute: AuthenticatedMUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
